-- Billing: consultations, payments, webhook events.
--
--   psql -h 127.0.0.1 -U product_owner -d law_agent -v ON_ERROR_STOP=1 \
--        -f backend/prisma/migrations/0002_billing.sql
--
-- Hand-written rather than generated by `prisma migrate dev`, for one concrete
-- reason: migrate needs a SHADOW DATABASE, which means CREATEDB on the
-- migrating role. `product_owner` deliberately does not have it — the whole
-- role design is about roles holding the least privilege that works. Explicit
-- DDL applied as the owner, then `prisma db pull` to sync the schema, keeps
-- that intact and matches how the `ai` schema is migrated.
--
-- Run as product_owner, so ALTER DEFAULT PRIVILEGES grants product_service
-- access automatically (see product/sql/bootstrap_product.sql).

BEGIN;

-- A consultation is the thing being sold: a lawyer's attention on one
-- conversation. It belongs to a user, so unlike anything the AI service owns,
-- this CAN be a real foreign key with a real cascade — both tables are in
-- `public` and the same service owns them.
CREATE TABLE IF NOT EXISTS public.consultations (
    id              VARCHAR(32) PRIMARY KEY,
    user_id         VARCHAR(32) NOT NULL
                    REFERENCES public.users (id) ON DELETE CASCADE,

    -- Which conversation the lawyer is taking over. OPAQUE, and deliberately
    -- NOT a foreign key: ai.sessions belongs to the other service, this role
    -- has no grant on that schema, and a cross-schema FK would mean
    -- coordinated migrations forever. Same rule the AI service follows in the
    -- other direction with user_id.
    ai_session_id   VARCHAR(32),

    status          VARCHAR(16) NOT NULL DEFAULT 'pending',
    amount_cents    INTEGER     NOT NULL,
    currency        VARCHAR(3)  NOT NULL DEFAULT 'EGP',

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at         TIMESTAMPTZ,

    -- Telling the AI service to escalate is a cross-service call that can
    -- fail. Recording the outcome here means a failure costs a retry rather
    -- than a paying client whose lawyer never got the conversation — the same
    -- shape as erasure_requests, and for the same reason.
    escalated_at    TIMESTAMPTZ,
    escalation_error TEXT,

    CONSTRAINT ck_consultations_status
        CHECK (status IN ('pending', 'paid', 'cancelled', 'refunded')),
    CONSTRAINT ck_consultations_amount CHECK (amount_cents > 0)
);

CREATE INDEX IF NOT EXISTS ix_consultations_user
    ON public.consultations (user_id, created_at DESC);

-- Paid but not yet escalated. This is the queue a monitor watches: money taken
-- and the service not yet delivered.
CREATE INDEX IF NOT EXISTS ix_consultations_unescalated
    ON public.consultations (paid_at)
    WHERE status = 'paid' AND escalated_at IS NULL;

CREATE TABLE IF NOT EXISTS public.payments (
    id                VARCHAR(32) PRIMARY KEY,
    consultation_id   VARCHAR(32) NOT NULL
                      REFERENCES public.consultations (id) ON DELETE CASCADE,

    provider          VARCHAR(24) NOT NULL DEFAULT 'paymob',
    provider_order_id VARCHAR(64),
    provider_txn_id   VARCHAR(64) NOT NULL,

    amount_cents      INTEGER     NOT NULL,
    currency          VARCHAR(3)  NOT NULL,
    status            VARCHAR(16) NOT NULL,

    -- The gateway's own payload, kept verbatim. When a client disputes a
    -- charge months later, "what did Paymob actually send us" is the only
    -- question that matters, and a parsed subset never answers it.
    raw               JSONB,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- The idempotency key. Payment gateways retry, and without this a retried
    -- webhook is a second payment row and a second escalation.
    CONSTRAINT uq_payments_provider_txn UNIQUE (provider, provider_txn_id),
    CONSTRAINT ck_payments_status
        CHECK (status IN ('success', 'failed', 'pending', 'refunded', 'voided'))
);

CREATE INDEX IF NOT EXISTS ix_payments_consultation
    ON public.payments (consultation_id);

-- Every webhook delivery, valid or not.
--
-- Recorded BEFORE processing and including ones whose signature failed,
-- because "we never received it" and "we received it and rejected it" are
-- different conversations to have with a payment provider, and only one of
-- them is your fault.
CREATE TABLE IF NOT EXISTS public.webhook_events (
    id                VARCHAR(32) PRIMARY KEY,
    provider          VARCHAR(24) NOT NULL,
    provider_event_id VARCHAR(64) NOT NULL,
    signature_valid   BOOLEAN     NOT NULL,
    received_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at      TIMESTAMPTZ,
    error             TEXT,
    payload           JSONB       NOT NULL,

    CONSTRAINT uq_webhook_event UNIQUE (provider, provider_event_id)
);

CREATE INDEX IF NOT EXISTS ix_webhook_unprocessed
    ON public.webhook_events (received_at)
    WHERE processed_at IS NULL;

COMMIT;
